//
//  NSURLRequest+AppCore.h
//  DVAppCore
//
//  Created by Denis Vashkovski on 15/02/16.
//  Copyright © 2016 Denis Vashkovski. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "NSObject+AppCore.h"
#import "ACURLConnectionManager.h"

AC_EXTERN_STRING_H(APIServerURL)

@interface NSURLRequest(AppCore)
+ (NSURLRequest *)ac_requestGetByLink:(NSString *)link parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields;
+ (NSURLRequest *)ac_requestGetByLink:(NSString *)link parameters:(NSDictionary *)parameters;
+ (NSURLRequest *)ac_requestGetByLink:(NSString *)link;

+ (NSURLRequest *)ac_requestGetForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields;
+ (NSURLRequest *)ac_requestGetForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters;
+ (NSURLRequest *)ac_requestGetForRootLinkByHref:(NSString *)href;

+ (NSURLRequest *)ac_requestPostByLink:(NSString *)link body:(NSData *)body headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPostByLink:(NSString *)link parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPostForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPostForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields;
+ (NSURLRequest *)ac_requestPostForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters;
+ (NSURLRequest *)ac_requestPostForRootLinkByHref:(NSString *)href;

+ (NSURLRequest *)ac_requestPutByLink:(NSString *)link body:(NSData *)body headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPutByLink:(NSString *)link parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPutForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestPutForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields;
+ (NSURLRequest *)ac_requestPutForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters;
+ (NSURLRequest *)ac_requestPutForRootLinkByHref:(NSString *)href;

+ (NSURLRequest *)ac_requestDeleteByLink:(NSString *)link body:(NSData *)body headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestDeleteByLink:(NSString *)link parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestDeleteForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields data:(NSArray<NSData *> *)data;
+ (NSURLRequest *)ac_requestDeleteForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters headerFields:(NSDictionary *)headerFields;
+ (NSURLRequest *)ac_requestDeleteForRootLinkByHref:(NSString *)href parameters:(NSDictionary *)parameters;
+ (NSURLRequest *)ac_requestDeleteForRootLinkByHref:(NSString *)href;

- (void)ac_sendAsynchronousWithCompletionHandler:(ACURLCompletionHadler)handler;
- (id)ac_sendSynchronousWithResponse:(NSHTTPURLResponse **)response;
@end

#pragma mark - HTTP method
#define AC_HTTP_METHOD_CONNECT              @"CONNECT"
#define AC_HTTP_METHOD_DELETE               @"DELETE"
#define AC_HTTP_METHOD_GET                  @"GET"
#define AC_HTTP_METHOD_HEAD                 @"HEAD"
#define AC_HTTP_METHOD_OPTIONS              @"OPTIONS"
#define AC_HTTP_METHOD_POST                 @"POST"
#define AC_HTTP_METHOD_PUT                  @"PUT"
#define AC_HTTP_METHOD_TRACE                @"TRACE"
#define AC_HTTP_METHOD_ACL                  @"ACL"
#define AC_HTTP_METHOD_BASELINE_CONTROL     @"BASELINE-CONTROL"
#define AC_HTTP_METHOD_BIND                 @"BIND"
#define AC_HTTP_METHOD_CHECKIN              @"CHECKIN"
#define AC_HTTP_METHOD_CHECKOUT             @"CHECKOUT"
#define AC_HTTP_METHOD_COPY                 @"COPY"
#define AC_HTTP_METHOD_LABEL                @"LABEL"
#define AC_HTTP_METHOD_LINK                 @"LINK"
#define AC_HTTP_METHOD_LOCK                 @"LOCK"
#define AC_HTTP_METHOD_MERGE                @"MERGE"
#define AC_HTTP_METHOD_MKACTIVITY           @"MKACTIVITY"
#define AC_HTTP_METHOD_MKCALENDAR           @"MKCALENDAR"
#define AC_HTTP_METHOD_MKCOL                @"MKCOL"
#define AC_HTTP_METHOD_MKREDIRECTREF        @"MKREDIRECTREF"
#define AC_HTTP_METHOD_MKWORKSPACE          @"MKWORKSPACE"
#define AC_HTTP_METHOD_MOVE                 @"MOVE"
#define AC_HTTP_METHOD_ORDERPATCH           @"ORDERPATCH"
#define AC_HTTP_METHOD_PATCH                @"PATCH"
#define AC_HTTP_METHOD_PROPFIND             @"PROPFIND"
#define AC_HTTP_METHOD_PROPPATCH            @"PROPPATCH"
#define AC_HTTP_METHOD_REBIND               @"REBIND"
#define AC_HTTP_METHOD_REPORT               @"REPORT"
#define AC_HTTP_METHOD_SEARCH               @"SEARCH"
#define AC_HTTP_METHOD_UNBIND               @"UNBIND"
#define AC_HTTP_METHOD_UNCHECKOUT           @"UNCHECKOUT"
#define AC_HTTP_METHOD_UNLINK               @"UNLINK"
#define AC_HTTP_METHOD_UNLOCK               @"UNLOCK"
#define AC_HTTP_METHOD_UPDATE               @"UPDATE"
#define AC_HTTP_METHOD_UPDATEREDIRECTREF    @"UPDATEREDIRECTREF"
#define AC_HTTP_METHOD_VERSION_CONTROL      @"VERSION-CONTROL"

#pragma mark - HTTP header key
#define AC_HTTP_HEADER_KEY_CONTENT_ENCODING @"Content-Encoding"
#define AC_HTTP_HEADER_KEY_CONTENT_LANGUAGE @"Content-Language"
#define AC_HTTP_HEADER_KEY_CONTENT_LOCATION @"Content-Location"
#define AC_HTTP_HEADER_KEY_CONTENT_TYPE @"Content-Type"
#define AC_HTTP_HEADER_KEY_CONTENT_LENGTH @"Content-Length"
#define AC_HTTP_HEADER_KEY_CONTENT_RANGE @"Content-Range"
#define AC_HTTP_HEADER_KEY_TRANSFER_ENCODING @"Transfer-Encoding"
#define AC_HTTP_HEADER_KEY_CACHE_CONTROL @"Cache-Control"
#define AC_HTTP_HEADER_KEY_EXPECT @"Expect"
#define AC_HTTP_HEADER_KEY_HOST @"Host"
#define AC_HTTP_HEADER_KEY_HTTP2_SETTINGS @"HTTP2-Settings"
#define AC_HTTP_HEADER_KEY_MAX_FORWARDS @"Max-Forwards"
#define AC_HTTP_HEADER_KEY_PRAGMA @"Pragma"
#define AC_HTTP_HEADER_KEY_RANGE @"Range"
#define AC_HTTP_HEADER_KEY_TE @"TE"
#define AC_HTTP_HEADER_KEY_IF_MATCH @"If-Match"
#define AC_HTTP_HEADER_KEY_IF_MODIFIED_SINCE @"If-Modified-Since"
#define AC_HTTP_HEADER_KEY_IF_NONE_MATCH @"If-None-Match"
#define AC_HTTP_HEADER_KEY_IF_RANGE @"If-Range"
#define AC_HTTP_HEADER_KEY_IF_UNMODIFIED_SINCE @"If-Unmodified-Since"
#define AC_HTTP_HEADER_KEY_ACCEPT @"Accept"
#define AC_HTTP_HEADER_KEY_ACCEPT_CHARSET @"Accept-Charset"
#define AC_HTTP_HEADER_KEY_ACCEPT_ENCODING @"Accept-Encoding"
#define AC_HTTP_HEADER_KEY_ACCEPT_LANGUAGE @"Accept-Language"
#define AC_HTTP_HEADER_KEY_AUTHORIZATION @"Authorization"
#define AC_HTTP_HEADER_KEY_PROXY_AUTHORIZATION @"Proxy-Authorization"
#define AC_HTTP_HEADER_KEY_DNT @"DNT"
#define AC_HTTP_HEADER_KEY_FROM @"From"
#define AC_HTTP_HEADER_KEY_REFERER @"Referer"
#define AC_HTTP_HEADER_KEY_USER_AGENT @"User-Agent"
#define AC_HTTP_HEADER_KEY_AGE @"Age"
#define AC_HTTP_HEADER_KEY_EXPIRES @"Expires"
#define AC_HTTP_HEADER_KEY_DATE @"Date"
#define AC_HTTP_HEADER_KEY_LOCATION @"Location"
#define AC_HTTP_HEADER_KEY_RETRY_AFTER @"Retry-After"
#define AC_HTTP_HEADER_KEY_TK @"Tk"
#define AC_HTTP_HEADER_KEY_VARY @"Vary"
#define AC_HTTP_HEADER_KEY_WARNING @"Warning"
#define AC_HTTP_HEADER_KEY_ETAG @"ETag"
#define AC_HTTP_HEADER_KEY_LAST_MODIFIED @"Last-Modified"
#define AC_HTTP_HEADER_KEY_WWW_AUTHENTICATE @"WWW-Authenticate"
#define AC_HTTP_HEADER_KEY_PROXY_AUTHENTICATE @"Proxy-Authenticate"
#define AC_HTTP_HEADER_KEY_ACCEPT_RANGES @"Accept-Ranges"
#define AC_HTTP_HEADER_KEY_ALLOW @"Allow"
#define AC_HTTP_HEADER_KEY_SERVER @"Server"
#define AC_HTTP_HEADER_KEY_ACCEPT_PATCH @"Accept-Patch"
#define AC_HTTP_HEADER_KEY_ACCEPT_POST @"Accept-Post"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_CREDENTIALS @"Access-Control-Allow-Credentials"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_HEADERS @"Access-Control-Allow-Headers"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_METHODS @"Access-Control-Allow-Methods"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_ORIGIN @"Access-Control-Allow-Origin"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_EXPOSE_HEADERS @"Access-Control-Expose-Headers"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_MAX_AGE @"Access-Control-Max-Age"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_REQUEST_HEADERS @"Access-Control-Request-Headers"
#define AC_HTTP_HEADER_KEY_ACCESS_CONTROL_REQUEST_METHOD @"Access-Control-Request-Method"
#define AC_HTTP_HEADER_KEY_CONTENT_DISPOSITION @"Content-Disposition"
#define AC_HTTP_HEADER_KEY_CONTENT_SECURITY_POLICY @"Content-Security-Policy"
#define AC_HTTP_HEADER_KEY_CONTENT_SECURITY_POLICY_REPORT_ONLY @"Content-Security-Policy-Report-Only"
#define AC_HTTP_HEADER_KEY_COOKIE @"Cookie"
#define AC_HTTP_HEADER_KEY_FORWARDED @"Forwarded"
#define AC_HTTP_HEADER_KEY_LINK @"Link"
#define AC_HTTP_HEADER_KEY_ORIGIN @"Origin"
#define AC_HTTP_HEADER_KEY_PREFER @"Prefer"
#define AC_HTTP_HEADER_KEY_PREFERENCE_APPLIED @"Preference-Applied"
#define AC_HTTP_HEADER_KEY_SET_COOKIE @"Set-Cookie"
#define AC_HTTP_HEADER_KEY_STRICT_TRANSPORT_SECURITY @"Strict-Transport-Security"
#define AC_HTTP_HEADER_KEY_VIA @"Via"
#define AC_HTTP_HEADER_KEY_A_IM @"A-IM"
#define AC_HTTP_HEADER_KEY_ACCEPT_CH @"Accept-CH"
#define AC_HTTP_HEADER_KEY_ACCEPT_FEATURES @"Accept-Features"
#define AC_HTTP_HEADER_KEY_ALPN @"ALPN"
#define AC_HTTP_HEADER_KEY_ALT_SVC @"Alt-Svc"
#define AC_HTTP_HEADER_KEY_ALTERNATES @"Alternates"
#define AC_HTTP_HEADER_KEY_APPLY_TO_REDIRECT_REF @"Apply-To-Redirect-Ref"
#define AC_HTTP_HEADER_KEY_CH @"CH"
#define AC_HTTP_HEADER_KEY_CONTENT_BASE @"Content-Base"
#define AC_HTTP_HEADER_KEY_CONTENT_DPR @"Content-DPR"
#define AC_HTTP_HEADER_KEY_COOKIE2 @"Cookie2"
#define AC_HTTP_HEADER_KEY_DASL @"DASL"
#define AC_HTTP_HEADER_KEY_DAV @"DAV"
#define AC_HTTP_HEADER_KEY_DELTA_BASE @"Delta-Base"
#define AC_HTTP_HEADER_KEY_DEPTH @"Depth"
#define AC_HTTP_HEADER_KEY_DESTINATION @"Destination"
#define AC_HTTP_HEADER_KEY_DPR @"DPR"
#define AC_HTTP_HEADER_KEY_ENCRYPTION @"Encryption"
#define AC_HTTP_HEADER_KEY_ENCRYPTION_KEY @"Encryption-Key"
#define AC_HTTP_HEADER_KEY_IM @"IM"
#define AC_HTTP_HEADER_KEY_IF @"If"
#define AC_HTTP_HEADER_KEY_IF_SCHEDULE_TAG_MATCH @"If-Schedule-Tag-Match"
#define AC_HTTP_HEADER_KEY_KEY @"Key"
#define AC_HTTP_HEADER_KEY_LAST_EVENT_ID @"Last-Event-ID"
#define AC_HTTP_HEADER_KEY_LINK_TEMPLATE @"Link-Template"
#define AC_HTTP_HEADER_KEY_LOCK_TOKEN @"Lock-Token"
#define AC_HTTP_HEADER_KEY_MD @"MD"
#define AC_HTTP_HEADER_KEY_NEGOTIATE @"Negotiate"
#define AC_HTTP_HEADER_KEY_NICE @"Nice"
#define AC_HTTP_HEADER_KEY_OVERWRITE @"Overwrite"
#define AC_HTTP_HEADER_KEY_POE @"POE"
#define AC_HTTP_HEADER_KEY_POE_LINKS @"POE-Links"
#define AC_HTTP_HEADER_KEY_REDIRECT_REF @"Redirect-Ref"
#define AC_HTTP_HEADER_KEY_RW @"RW"
#define AC_HTTP_HEADER_KEY_SCHEDULE_REPLY @"Schedule-Reply"
#define AC_HTTP_HEADER_KEY_SCHEDULE_TAG @"Schedule-Tag"
#define AC_HTTP_HEADER_KEY_SEC_WEBSOCKET_ACCEPT @"Sec-WebSocket-Accept"
#define AC_HTTP_HEADER_KEY_SEC_WEBSOCKET_EXTENSIONS @"Sec-WebSocket-Extensions"
#define AC_HTTP_HEADER_KEY_SEC_WEBSOCKET_KEY @"Sec-WebSocket-Key"
#define AC_HTTP_HEADER_KEY_SEC_WEBSOCKET_PROTOCOL @"Sec-WebSocket-Protocol"
#define AC_HTTP_HEADER_KEY_SEC_WEBSOCKET_VERSION @"Sec-WebSocket-Version"
#define AC_HTTP_HEADER_KEY_SET_COOKIE2 @"Set-Cookie2"
#define AC_HTTP_HEADER_KEY_SLUG @"SLUG"
#define AC_HTTP_HEADER_KEY_STATUS_URI @"Status-URI"
#define AC_HTTP_HEADER_KEY_SUNSET @"Sunset"
#define AC_HTTP_HEADER_KEY_SURROGATE_CAPABILITY @"Surrogate-Capability"
#define AC_HTTP_HEADER_KEY_SURROGATE_CONTROL @"Surrogate-Control"
#define AC_HTTP_HEADER_KEY_TCN @"TCN"
#define AC_HTTP_HEADER_KEY_TIMEOUT @"Timeout"
#define AC_HTTP_HEADER_KEY_VARIANT_VARY @"Variant-Vary"
#define AC_HTTP_HEADER_KEY_X_FRAME_OPTIONS @"X-Frame-Options"

#pragma mark - HTTP content type
#define AC_CONTENT_TYPE_APPLICATION_X_WWW_FORM_URLENCODED @"application/x-www-form-urlencoded"
#define AC_CONTENT_TYPE_APPLICATION_1D_INTERLEAVED_PARITYFEC @"application/1d-interleaved-parityfec"
#define AC_CONTENT_TYPE_APPLICATION_BATCH_SMTP @"application/batch-SMTP"
#define AC_CONTENT_TYPE_APPLICATION_CALL_COMPLETION @"application/call-completion"
#define AC_CONTENT_TYPE_APPLICATION_CALS_1840 @"application/CALS-1840"
#define AC_CONTENT_TYPE_APPLICATION_CBOR @"application/cbor"
#define AC_CONTENT_TYPE_APPLICATION_CDMI_CAPABILITY @"application/cdmi-capability"
#define AC_CONTENT_TYPE_APPLICATION_CDMI_CONTAINER @"application/cdmi-container"
#define AC_CONTENT_TYPE_APPLICATION_CDMI_DOMAIN @"application/cdmi-domain"
#define AC_CONTENT_TYPE_APPLICATION_CDMI_OBJECT @"application/cdmi-object"
#define AC_CONTENT_TYPE_APPLICATION_CDMI_QUEUE @"application/cdmi-queue"
#define AC_CONTENT_TYPE_APPLICATION_CDNI @"application/cdni"
#define AC_CONTENT_TYPE_APPLICATION_CFW @"application/cfw"
#define AC_CONTENT_TYPE_APPLICATION_CMS @"application/cms"
#define AC_CONTENT_TYPE_APPLICATION_CSRATTRS @"application/csrattrs"
#define AC_CONTENT_TYPE_APPLICATION_DICOM @"application/dicom"
#define AC_CONTENT_TYPE_APPLICATION_DNS @"application/dns"
#define AC_CONTENT_TYPE_APPLICATION_DVCS @"application/dvcs"
#define AC_CONTENT_TYPE_APPLICATION_ECMASCRIPT @"application/ecmascript"
#define AC_CONTENT_TYPE_APPLICATION_EDI_CONSENT @"application/EDI-consent"
#define AC_CONTENT_TYPE_APPLICATION_EDIFACT @"application/EDIFACT"
#define AC_CONTENT_TYPE_APPLICATION_EDI_X12 @"application/EDI-X12"
#define AC_CONTENT_TYPE_APPLICATION_ENCAPRTP @"application/encaprtp"
#define AC_CONTENT_TYPE_APPLICATION_EXAMPLE @"application/example"
#define AC_CONTENT_TYPE_APPLICATION_FITS @"application/fits"
#define AC_CONTENT_TYPE_APPLICATION_FONT_TDPFR @"application/font-tdpfr"
#define AC_CONTENT_TYPE_APPLICATION_GZIP @"application/gzip"
#define AC_CONTENT_TYPE_APPLICATION_H224 @"application/H224"
#define AC_CONTENT_TYPE_APPLICATION_HTTP @"application/http"
#define AC_CONTENT_TYPE_APPLICATION_IBE_PP_DATA @"application/ibe-pp-data"
#define AC_CONTENT_TYPE_APPLICATION_INDEX @"application/index"
#define AC_CONTENT_TYPE_APPLICATION_IOTP @"application/iotp"
#define AC_CONTENT_TYPE_APPLICATION_IPFIX @"application/ipfix"
#define AC_CONTENT_TYPE_APPLICATION_IPP @"application/ipp"
#define AC_CONTENT_TYPE_APPLICATION_ISUP @"application/isup"
#define AC_CONTENT_TYPE_APPLICATION_JAVASCRIPT @"application/javascript"
#define AC_CONTENT_TYPE_APPLICATION_JOSE @"application/jose"
#define AC_CONTENT_TYPE_APPLICATION_JSON @"application/json"
#define AC_CONTENT_TYPE_APPLICATION_JSON_SEQ @"application/json-seq"
#define AC_CONTENT_TYPE_APPLICATION_JWT @"application/jwt"
#define AC_CONTENT_TYPE_APPLICATION_LINK_FORMAT @"application/link-format"
#define AC_CONTENT_TYPE_APPLICATION_MARC @"application/marc"
#define AC_CONTENT_TYPE_APPLICATION_MBOX @"application/mbox"
#define AC_CONTENT_TYPE_APPLICATION_MIKEY @"application/mikey"
#define AC_CONTENT_TYPE_APPLICATION_MOSS_KEYS @"application/moss-keys"
#define AC_CONTENT_TYPE_APPLICATION_MOSS_SIGNATURE @"application/moss-signature"
#define AC_CONTENT_TYPE_APPLICATION_MOSSKEY_DATA @"application/mosskey-data"
#define AC_CONTENT_TYPE_APPLICATION_MOSSKEY_REQUEST @"application/mosskey-request"
#define AC_CONTENT_TYPE_APPLICATION_MP21 @"application/mp21"
#define AC_CONTENT_TYPE_APPLICATION_MP4 @"application/mp4"
#define AC_CONTENT_TYPE_APPLICATION_MPEG4_GENERIC @"application/mpeg4-generic"
#define AC_CONTENT_TYPE_APPLICATION_MPEG4_IOD @"application/mpeg4-iod"
#define AC_CONTENT_TYPE_APPLICATION_MPEG4_IOD_XMT @"application/mpeg4-iod-xmt"
#define AC_CONTENT_TYPE_APPLICATION_MXF @"application/mxf"
#define AC_CONTENT_TYPE_APPLICATION_NASDATA @"application/nasdata"
#define AC_CONTENT_TYPE_APPLICATION_NEWS_CHECKGROUPS @"application/news-checkgroups"
#define AC_CONTENT_TYPE_APPLICATION_NEWS_GROUPINFO @"application/news-groupinfo"
#define AC_CONTENT_TYPE_APPLICATION_NEWS_TRANSMISSION @"application/news-transmission"
#define AC_CONTENT_TYPE_APPLICATION_OCSP_REQUEST @"application/ocsp-request"
#define AC_CONTENT_TYPE_APPLICATION_OCSP_RESPONSE @"application/ocsp-response"
#define AC_CONTENT_TYPE_APPLICATION_OCTET_STREAM @"application/octet-stream"
#define AC_CONTENT_TYPE_APPLICATION_ODA @"application/oda"
#define AC_CONTENT_TYPE_APPLICATION_OGG @"application/ogg"
#define AC_CONTENT_TYPE_APPLICATION_PDF @"application/pdf"
#define AC_CONTENT_TYPE_APPLICATION_PGP_ENCRYPTED @"application/pgp-encrypted"
#define AC_CONTENT_TYPE_APPLICATION_PGP_SIGNATURE @"application/pgp-signature"
#define AC_CONTENT_TYPE_APPLICATION_PKCS10 @"application/pkcs10"
#define AC_CONTENT_TYPE_APPLICATION_PKCS7_MIME @"application/pkcs7-mime"
#define AC_CONTENT_TYPE_APPLICATION_PKCS7_SIGNATURE @"application/pkcs7-signature"
#define AC_CONTENT_TYPE_APPLICATION_PKCS8 @"application/pkcs8"
#define AC_CONTENT_TYPE_APPLICATION_PKIX_ATTR_CERT @"application/pkix-attr-cert"
#define AC_CONTENT_TYPE_APPLICATION_PKIX_CERT @"application/pkix-cert"
#define AC_CONTENT_TYPE_APPLICATION_PKIX_CRL @"application/pkix-crl"
#define AC_CONTENT_TYPE_APPLICATION_PKIX_PKIPATH @"application/pkix-pkipath"
#define AC_CONTENT_TYPE_APPLICATION_PKIXCMP @"application/pkixcmp"
#define AC_CONTENT_TYPE_APPLICATION_POSTSCRIPT @"application/postscript"
#define AC_CONTENT_TYPE_APPLICATION_QSIG @"application/qsig"
#define AC_CONTENT_TYPE_APPLICATION_RAPTORFEC @"application/raptorfec"
#define AC_CONTENT_TYPE_APPLICATION_REMOTE_PRINTING @"application/remote-printing"
#define AC_CONTENT_TYPE_APPLICATION_RPKI_GHOSTBUSTERS @"application/rpki-ghostbusters"
#define AC_CONTENT_TYPE_APPLICATION_RPKI_MANIFEST @"application/rpki-manifest"
#define AC_CONTENT_TYPE_APPLICATION_RPKI_ROA @"application/rpki-roa"
#define AC_CONTENT_TYPE_APPLICATION_RPKI_UPDOWN @"application/rpki-updown"
#define AC_CONTENT_TYPE_APPLICATION_RTPLOOPBACK @"application/rtploopback"
#define AC_CONTENT_TYPE_APPLICATION_RTX @"application/rtx"
#define AC_CONTENT_TYPE_APPLICATION_SCVP_CV_REQUEST @"application/scvp-cv-request"
#define AC_CONTENT_TYPE_APPLICATION_SCVP_CV_RESPONSE @"application/scvp-cv-response"
#define AC_CONTENT_TYPE_APPLICATION_SCVP_VP_REQUEST @"application/scvp-vp-request"
#define AC_CONTENT_TYPE_APPLICATION_SCVP_VP_RESPONSE @"application/scvp-vp-response"
#define AC_CONTENT_TYPE_APPLICATION_SDP @"application/sdp"
#define AC_CONTENT_TYPE_APPLICATION_SGML @"application/sgml"
#define AC_CONTENT_TYPE_APPLICATION_SIEVE @"application/sieve"
#define AC_CONTENT_TYPE_APPLICATION_SIMPLE_MESSAGE_SUMMARY @"application/simple-message-summary"
#define AC_CONTENT_TYPE_APPLICATION_SMPTE336M @"application/smpte336m"
#define AC_CONTENT_TYPE_APPLICATION_SQL @"application/sql"
#define AC_CONTENT_TYPE_APPLICATION_SRGS @"application/srgs"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_APEX_UPDATE @"application/tamp-apex-update"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_APEX_UPDATE_CONFIRM @"application/tamp-apex-update-confirm"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_COMMUNITY_UPDATE @"application/tamp-community-update"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_COMMUNITY_UPDATE_CONFIRM @"application/tamp-community-update-confirm"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_ERROR @"application/tamp-error"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_SEQUENCE_ADJUST @"application/tamp-sequence-adjust"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_SEQUENCE_ADJUST_CONFIRM @"application/tamp-sequence-adjust-confirm"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_STATUS_QUERY @"application/tamp-status-query"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_STATUS_RESPONSE @"application/tamp-status-response"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_UPDATE @"application/tamp-update"
#define AC_CONTENT_TYPE_APPLICATION_TAMP_UPDATE_CONFIRM @"application/tamp-update-confirm"
#define AC_CONTENT_TYPE_APPLICATION_TIMESTAMP_QUERY @"application/timestamp-query"
#define AC_CONTENT_TYPE_APPLICATION_TIMESTAMP_REPLY @"application/timestamp-reply"
#define AC_CONTENT_TYPE_APPLICATION_TIMESTAMPED_DATA @"application/timestamped-data"
#define AC_CONTENT_TYPE_APPLICATION_ULPFEC @"application/ulpfec"
#define AC_CONTENT_TYPE_APPLICATION_VEMMI @"application/vemmi"
#define AC_CONTENT_TYPE_APPLICATION_VQ_RTCPXR @"application/vq-rtcpxr"
#define AC_CONTENT_TYPE_APPLICATION_WHOISPP_QUERY @"application/whoispp-query"
#define AC_CONTENT_TYPE_APPLICATION_WHOISPP_RESPONSE @"application/whoispp-response"
#define AC_CONTENT_TYPE_APPLICATION_X400_BP @"application/x400-bp"
#define AC_CONTENT_TYPE_APPLICATION_XML @"application/xml"
#define AC_CONTENT_TYPE_APPLICATION_XML_DTD @"application/xml-dtd"
#define AC_CONTENT_TYPE_APPLICATION_XML_EXTERNAL_PARSED_ENTITY @"application/xml-external-parsed-entity"
#define AC_CONTENT_TYPE_APPLICATION_YANG @"application/yang"
#define AC_CONTENT_TYPE_APPLICATION_ZLIB @"application/zlib"
#define AC_CONTENT_TYPE_AUDIO_1D_INTERLEAVED_PARITYFEC @"audio/1d-interleaved-parityfec"
#define AC_CONTENT_TYPE_AUDIO_32KADPCM @"audio/32kadpcm"
#define AC_CONTENT_TYPE_AUDIO_3GPP @"audio/3gpp"
#define AC_CONTENT_TYPE_AUDIO_3GPP2 @"audio/3gpp2"
#define AC_CONTENT_TYPE_AUDIO_AC3 @"audio/ac3"
#define AC_CONTENT_TYPE_AUDIO_AMR @"audio/AMR"
#define AC_CONTENT_TYPE_AUDIO_AMR_WB @"audio/AMR-WB"
#define AC_CONTENT_TYPE_AUDIO_APTX @"audio/aptx"
#define AC_CONTENT_TYPE_AUDIO_ASC @"audio/asc"
#define AC_CONTENT_TYPE_AUDIO_ATRAC_ADVANCED_LOSSLESS @"audio/ATRAC-ADVANCED-LOSSLESS"
#define AC_CONTENT_TYPE_AUDIO_ATRAC_X @"audio/ATRAC-X"
#define AC_CONTENT_TYPE_AUDIO_ATRAC3 @"audio/ATRAC3"
#define AC_CONTENT_TYPE_AUDIO_BASIC @"audio/basic"
#define AC_CONTENT_TYPE_AUDIO_BV16 @"audio/BV16"
#define AC_CONTENT_TYPE_AUDIO_BV32 @"audio/BV32"
#define AC_CONTENT_TYPE_AUDIO_CLEARMODE @"audio/clearmode"
#define AC_CONTENT_TYPE_AUDIO_CN @"audio/CN"
#define AC_CONTENT_TYPE_AUDIO_DAT12 @"audio/DAT12"
#define AC_CONTENT_TYPE_AUDIO_DLS @"audio/dls"
#define AC_CONTENT_TYPE_AUDIO_DSR_ES201108 @"audio/dsr-es201108"
#define AC_CONTENT_TYPE_AUDIO_DSR_ES202050 @"audio/dsr-es202050"
#define AC_CONTENT_TYPE_AUDIO_DSR_ES202211 @"audio/dsr-es202211"
#define AC_CONTENT_TYPE_AUDIO_DSR_ES202212 @"audio/dsr-es202212"
#define AC_CONTENT_TYPE_AUDIO_DV @"audio/DV"
#define AC_CONTENT_TYPE_AUDIO_DVI4 @"audio/DVI4"
#define AC_CONTENT_TYPE_AUDIO_EAC3 @"audio/eac3"
#define AC_CONTENT_TYPE_AUDIO_ENCAPRTP @"audio/encaprtp"
#define AC_CONTENT_TYPE_AUDIO_EVRC @"audio/EVRC"
#define AC_CONTENT_TYPE_AUDIO_EVRC_QCP @"audio/EVRC-QCP"
#define AC_CONTENT_TYPE_AUDIO_EVRC0 @"audio/EVRC0"
#define AC_CONTENT_TYPE_AUDIO_EVRC1 @"audio/EVRC1"
#define AC_CONTENT_TYPE_AUDIO_EVRCB @"audio/EVRCB"
#define AC_CONTENT_TYPE_AUDIO_EVRCB0 @"audio/EVRCB0"
#define AC_CONTENT_TYPE_AUDIO_EVRCB1 @"audio/EVRCB1"
#define AC_CONTENT_TYPE_AUDIO_EVRCNW @"audio/EVRCNW"
#define AC_CONTENT_TYPE_AUDIO_EVRCNW0 @"audio/EVRCNW0"
#define AC_CONTENT_TYPE_AUDIO_EVRCNW1 @"audio/EVRCNW1"
#define AC_CONTENT_TYPE_AUDIO_EVRCWB @"audio/EVRCWB"
#define AC_CONTENT_TYPE_AUDIO_EVRCWB0 @"audio/EVRCWB0"
#define AC_CONTENT_TYPE_AUDIO_EVRCWB1 @"audio/EVRCWB1"
#define AC_CONTENT_TYPE_AUDIO_EXAMPLE @"audio/example"
#define AC_CONTENT_TYPE_AUDIO_FWDRED @"audio/fwdred"
#define AC_CONTENT_TYPE_AUDIO_G711_0 @"audio/G711-0"
#define AC_CONTENT_TYPE_AUDIO_G719 @"audio/G719"
#define AC_CONTENT_TYPE_AUDIO_G7221 @"audio/G7221"
#define AC_CONTENT_TYPE_AUDIO_G722 @"audio/G722"
#define AC_CONTENT_TYPE_AUDIO_G723 @"audio/G723"
#define AC_CONTENT_TYPE_AUDIO_G726_16 @"audio/G726-16"
#define AC_CONTENT_TYPE_AUDIO_G726_24 @"audio/G726-24"
#define AC_CONTENT_TYPE_AUDIO_G726_32 @"audio/G726-32"
#define AC_CONTENT_TYPE_AUDIO_G726_40 @"audio/G726-40"
#define AC_CONTENT_TYPE_AUDIO_G728 @"audio/G728"
#define AC_CONTENT_TYPE_AUDIO_G729 @"audio/G729"
#define AC_CONTENT_TYPE_AUDIO_G729D @"audio/G729D"
#define AC_CONTENT_TYPE_AUDIO_G729E @"audio/G729E"
#define AC_CONTENT_TYPE_AUDIO_GSM @"audio/GSM"
#define AC_CONTENT_TYPE_AUDIO_GSM_EFR @"audio/GSM-EFR"
#define AC_CONTENT_TYPE_AUDIO_GSM_HR_08 @"audio/GSM-HR-08"
#define AC_CONTENT_TYPE_AUDIO_ILBC @"audio/iLBC"
#define AC_CONTENT_TYPE_AUDIO_L8 @"audio/L8"
#define AC_CONTENT_TYPE_AUDIO_L16 @"audio/L16"
#define AC_CONTENT_TYPE_AUDIO_L20 @"audio/L20"
#define AC_CONTENT_TYPE_AUDIO_L24 @"audio/L24"
#define AC_CONTENT_TYPE_AUDIO_LPC @"audio/LPC"
#define AC_CONTENT_TYPE_AUDIO_MOBILE_XMF @"audio/mobile-xmf"
#define AC_CONTENT_TYPE_AUDIO_MPA @"audio/MPA"
#define AC_CONTENT_TYPE_AUDIO_MP4 @"audio/mp4"
#define AC_CONTENT_TYPE_AUDIO_MP4A_LATM @"audio/MP4A-LATM"
#define AC_CONTENT_TYPE_AUDIO_MPA_ROBUST @"audio/mpa-robust"
#define AC_CONTENT_TYPE_AUDIO_MPEG @"audio/mpeg"
#define AC_CONTENT_TYPE_AUDIO_MPEG4_GENERIC @"audio/mpeg4-generic"
#define AC_CONTENT_TYPE_AUDIO_OGG @"audio/ogg"
#define AC_CONTENT_TYPE_AUDIO_OPUS @"audio/opus"
#define AC_CONTENT_TYPE_AUDIO_PCMA @"audio/PCMA"
#define AC_CONTENT_TYPE_AUDIO_PCMA_WB @"audio/PCMA-WB"
#define AC_CONTENT_TYPE_AUDIO_PCMU @"audio/PCMU"
#define AC_CONTENT_TYPE_AUDIO_PCMU_WB @"audio/PCMU-WB"
#define AC_CONTENT_TYPE_AUDIO_RAPTORFEC @"audio/raptorfec"
#define AC_CONTENT_TYPE_AUDIO_RED @"audio/RED"
#define AC_CONTENT_TYPE_AUDIO_RTPLOOPBACK @"audio/rtploopback"
#define AC_CONTENT_TYPE_AUDIO_RTP_MIDI @"audio/rtp-midi"
#define AC_CONTENT_TYPE_AUDIO_RTX @"audio/rtx"
#define AC_CONTENT_TYPE_AUDIO_SMV @"audio/SMV"
#define AC_CONTENT_TYPE_AUDIO_SMV0 @"audio/SMV0"
#define AC_CONTENT_TYPE_AUDIO_SMV_QCP @"audio/SMV-QCP"
#define AC_CONTENT_TYPE_AUDIO_SPEEX @"audio/speex"
#define AC_CONTENT_TYPE_AUDIO_T140C @"audio/t140c"
#define AC_CONTENT_TYPE_AUDIO_T38 @"audio/t38"
#define AC_CONTENT_TYPE_AUDIO_TELEPHONE_EVENT @"audio/telephone-event"
#define AC_CONTENT_TYPE_AUDIO_TONE @"audio/tone"
#define AC_CONTENT_TYPE_AUDIO_UEMCLIP @"audio/UEMCLIP"
#define AC_CONTENT_TYPE_AUDIO_ULPFEC @"audio/ulpfec"
#define AC_CONTENT_TYPE_AUDIO_VDVI @"audio/VDVI"
#define AC_CONTENT_TYPE_AUDIO_VMR_WB @"audio/VMR-WB"
#define AC_CONTENT_TYPE_AUDIO_VORBIS @"audio/vorbis"
#define AC_CONTENT_TYPE_AUDIO_VORBIS_CONFIG @"audio/vorbis-config"
#define AC_CONTENT_TYPE_MESSAGE_CPIM @"message/CPIM"
#define AC_CONTENT_TYPE_MESSAGE_DELIVERY_STATUS @"message/delivery-status"
#define AC_CONTENT_TYPE_MESSAGE_DISPOSITION_NOTIFICATION @"message/disposition-notification"
#define AC_CONTENT_TYPE_MESSAGE_EXAMPLE @"message/example"
#define AC_CONTENT_TYPE_MESSAGE_FEEDBACK_REPORT @"message/feedback-report"
#define AC_CONTENT_TYPE_MESSAGE_GLOBAL @"message/global"
#define AC_CONTENT_TYPE_MESSAGE_GLOBAL_DELIVERY_STATUS @"message/global-delivery-status"
#define AC_CONTENT_TYPE_MESSAGE_GLOBAL_DISPOSITION_NOTIFICATION @"message/global-disposition-notification"
#define AC_CONTENT_TYPE_MESSAGE_GLOBAL_HEADERS @"message/global-headers"
#define AC_CONTENT_TYPE_MESSAGE_HTTP @"message/http"
#define AC_CONTENT_TYPE_MESSAGE_S_HTTP @"message/s-http"
#define AC_CONTENT_TYPE_MESSAGE_SIP @"message/sip"
#define AC_CONTENT_TYPE_MESSAGE_SIPFRAG @"message/sipfrag"
#define AC_CONTENT_TYPE_MESSAGE_TRACKING_STATUS @"message/tracking-status"
#define AC_CONTENT_TYPE_MODEL_EXAMPLE @"model/example"
#define AC_CONTENT_TYPE_MULTIPART_BYTERANGES @"multipart/byteranges"
#define AC_CONTENT_TYPE_MULTIPART_ENCRYPTED @"multipart/encrypted"
#define AC_CONTENT_TYPE_MULTIPART_EXAMPLE @"multipart/example"
#define AC_CONTENT_TYPE_MULTIPART_FORM_DATA @"multipart/form-data"
#define AC_CONTENT_TYPE_MULTIPART_RELATED @"multipart/related"
#define AC_CONTENT_TYPE_MULTIPART_REPORT @"multipart/report"
#define AC_CONTENT_TYPE_MULTIPART_SIGNED @"multipart/signed"
#define AC_CONTENT_TYPE_MULTIPART_VOICE_MESSAGE @"multipart/voice-message"
#define AC_CONTENT_TYPE_TEXT_1D_INTERLEAVED_PARITYFEC @"text/1d-interleaved-parityfec"
#define AC_CONTENT_TYPE_TEXT_CALENDAR @"text/calendar"
#define AC_CONTENT_TYPE_TEXT_CSS @"text/css"
#define AC_CONTENT_TYPE_TEXT_CSV @"text/csv"
#define AC_CONTENT_TYPE_TEXT_DNS @"text/dns"
#define AC_CONTENT_TYPE_TEXT_ENCAPRTP @"text/encaprtp"
#define AC_CONTENT_TYPE_TEXT_EXAMPLE @"text/example"
#define AC_CONTENT_TYPE_TEXT_FWDRED @"text/fwdred"
#define AC_CONTENT_TYPE_TEXT_GRAMMAR_REF_LIST @"text/grammar-ref-list"
#define AC_CONTENT_TYPE_TEXT_MARKDOWN @"text/markdown"
#define AC_CONTENT_TYPE_TEXT_PARAMETERS @"text/parameters"
#define AC_CONTENT_TYPE_TEXT_RAPTORFEC @"text/raptorfec"
#define AC_CONTENT_TYPE_TEXT_RED @"text/RED"
#define AC_CONTENT_TYPE_TEXT_RFC822_HEADERS @"text/rfc822-headers"
#define AC_CONTENT_TYPE_TEXT_RTPLOOPBACK @"text/rtploopback"
#define AC_CONTENT_TYPE_TEXT_RTX @"text/rtx"
#define AC_CONTENT_TYPE_TEXT_SGML @"text/sgml"
#define AC_CONTENT_TYPE_TEXT_T140 @"text/t140"
#define AC_CONTENT_TYPE_TEXT_TROFF @"text/troff"
#define AC_CONTENT_TYPE_TEXT_ULPFEC @"text/ulpfec"
#define AC_CONTENT_TYPE_TEXT_URI_LIST @"text/uri-list"
#define AC_CONTENT_TYPE_TEXT_VCARD @"text/vcard"
#define AC_CONTENT_TYPE_TEXT_XML @"text/xml"
#define AC_CONTENT_TYPE_TEXT_XML_EXTERNAL_PARSED_ENTITY @"text/xml-external-parsed-entity"
#define AC_CONTENT_TYPE_VIDEO_1D_INTERLEAVED_PARITYFEC @"video/1d-interleaved-parityfec"
#define AC_CONTENT_TYPE_VIDEO_3GPP @"video/3gpp"
#define AC_CONTENT_TYPE_VIDEO_3GPP2 @"video/3gpp2"
#define AC_CONTENT_TYPE_VIDEO_3GPP_TT @"video/3gpp-tt"
#define AC_CONTENT_TYPE_VIDEO_BMPEG @"video/BMPEG"
#define AC_CONTENT_TYPE_VIDEO_BT656 @"video/BT656"
#define AC_CONTENT_TYPE_VIDEO_CELB @"video/CelB"
#define AC_CONTENT_TYPE_VIDEO_DV @"video/DV"
#define AC_CONTENT_TYPE_VIDEO_ENCAPRTP @"video/encaprtp"
#define AC_CONTENT_TYPE_VIDEO_EXAMPLE @"video/example"
#define AC_CONTENT_TYPE_VIDEO_H261 @"video/H261"
#define AC_CONTENT_TYPE_VIDEO_H263 @"video/H263"
#define AC_CONTENT_TYPE_VIDEO_H263_1998 @"video/H263-1998"
#define AC_CONTENT_TYPE_VIDEO_H263_2000 @"video/H263-2000"
#define AC_CONTENT_TYPE_VIDEO_H264 @"video/H264"
#define AC_CONTENT_TYPE_VIDEO_H264_RCDO @"video/H264-RCDO"
#define AC_CONTENT_TYPE_VIDEO_H264_SVC @"video/H264-SVC"
#define AC_CONTENT_TYPE_VIDEO_H265 @"video/H265"
#define AC_CONTENT_TYPE_VIDEO_JPEG @"video/JPEG"
#define AC_CONTENT_TYPE_VIDEO_JPEG2000 @"video/jpeg2000"
#define AC_CONTENT_TYPE_VIDEO_MJ2 @"video/mj2"
#define AC_CONTENT_TYPE_VIDEO_MP1S @"video/MP1S"
#define AC_CONTENT_TYPE_VIDEO_MP2P @"video/MP2P"
#define AC_CONTENT_TYPE_VIDEO_MP2T @"video/MP2T"
#define AC_CONTENT_TYPE_VIDEO_MP4 @"video/mp4"
#define AC_CONTENT_TYPE_VIDEO_MP4V_ES @"video/MP4V-ES"
#define AC_CONTENT_TYPE_VIDEO_MPV @"video/MPV"
#define AC_CONTENT_TYPE_VIDEO_MPEG4_GENERIC @"video/mpeg4-generic"
#define AC_CONTENT_TYPE_VIDEO_NV @"video/nv"
#define AC_CONTENT_TYPE_VIDEO_OGG @"video/ogg"
#define AC_CONTENT_TYPE_VIDEO_POINTER @"video/pointer"
#define AC_CONTENT_TYPE_VIDEO_QUICKTIME @"video/quicktime"
#define AC_CONTENT_TYPE_VIDEO_RAPTORFEC @"video/raptorfec"
#define AC_CONTENT_TYPE_VIDEO_RTPLOOPBACK @"video/rtploopback"
#define AC_CONTENT_TYPE_VIDEO_RTX @"video/rtx"
#define AC_CONTENT_TYPE_VIDEO_SMPTE292M @"video/SMPTE292M"
#define AC_CONTENT_TYPE_VIDEO_ULPFEC @"video/ulpfec"
#define AC_CONTENT_TYPE_VIDEO_VC1 @"video/vc1"
#define AC_CONTENT_TYPE_VIDEO_VP8 @"video/VP8"
